package com.lostsidewalk.cultivator

declare defaultKieSession
end

declare Map
    @typesafe(false)
end

declare Actuator
    @typesafe(false)
end

rule "plant temp GT 25 deg -> fan1 (on)"
when
    $sensorState: Map((this["plant1_temp"] > 25.0) || (this["plant2_temp"] > 25.0) || (this["plant3_temp"] > 25.0))
    $actuator: Actuator(name == "fan1") from $actuators.values()
then
    $actuator.setState(true);
end

rule "plant temp LE 25 deg -> fan1 (off)"
when
    $sensorState: Map((this["plant1_temp"] <= 25.0) && (this["plant2_temp"] <= 25.0) && (this["plant3_temp"] <= 25.0))
    $actuator: Actuator(name == "fan1") from $actuators.values()
then
    $actuator.setState(true);
end
